<?php

namespace CP_Library\Models;

use CP_Library\Exception;

/**
 * Source DB Class
 *
 * @since       1.0
 */

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * Source Class
 *
 * @since 1.0.0
 */
class Speaker extends Source {

	public static $type_key = 'speaker';

	public function init() {
		$this->post_type = 'cpl_speaker';
		$this->type = 'cpl_source';

		parent::init();
	}

	public static function get_type_id() {
		if ( ! $type = SourceType::get_by_title( self::$type_key ) ) {
			try {
				$type = SourceType::insert( [ 'title' => self::$type_key ] );
			} catch ( Exception $e ) {
				error_log( $e );
			}
		}

		return $type->id;
	}

	public static function insert( $data ) {
		$speaker = parent::insert( $data ); // TODO: Change the autogenerated stub
		$speaker->add_type();
		return $speaker;
	}

	public function update( $data = array() ) {
		$this->add_type();
		return parent::update( $data ); // TODO: Change the autogenerated stub
	}

	public function add_type() {
		$this->update_meta( [
			'key' => 'source_type',
			'value' => 1, // just set some positive value
			'source_type_id' => self::get_type_id()
		] );
	}
}
